url: http://ste.vet
author: Steve Taylor
title: Steve Taylor
description: A blog by Steve "Schtee" Taylor
twitter_username: schtee
github_username: schtee
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "redirects"
    values:
      layout: "redirect"

collections:
  redirects:
    output: true
    permalink: /s/:name/index.html
