url: http://ste.vet
author: Stephen Taylor
title: Stephen Taylor
description: A blog by Stephen "Schtee" Taylor
twitter_username: schtee
github_username: schtee
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
